# Generated by Django 5.0.14 on 2026-01-21 19:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_runs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentrun',
            name='input_prompt',
        ),
        migrations.AddField(
            model_name='agentrun',
            name='cost_usd',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='agentrun',
            name='input_params',
            field=models.JSONField(default=dict),
        ),
        migrations.CreateModel(
            name='RunStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step_type', models.CharField(max_length=50)),
                ('content', models.JSONField()),
                ('usage_tokens', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='agent_runs.agentrun')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.DeleteModel(
            name='AgentLog',
        ),
    ]
